#!/bin/sh
rm -rf /root/*
clear
cd /root
echo -e "\033[34m ************************************************\033[0m"
echo -e "\033[34m           欢迎使用OPENVPN快速安装助手\033[0m          "
echo -e "\033[34m ************************************************\033[0m"
echo -e "\033[37m    所有流控已全部本地化，永久使用，完全免费       \033[0m         "
echo -e "\033[34m ************************************************\033[0m"

echo -e "请选择要安装的流控类型："
echo -e "\033[31m1. 青云最新版            CentOS 7.x 64位 \033[0m"
echo -e "\033[32m2. FAS3.0最新版          CentOS 7.x 64位 \033[0m"
echo -e "\033[33m3. 快云6期优化版         CentOS 7.x 64位 \033[0m"
echo -e "\033[34m4. 服务器测速                            \033[0m"
echo -n "请输入安装选项并回车："

read install_type
if [ $install_type == 1 ];then
     wget -q https://raw.githubusercontent.com/Demontisa/ML/main/op/qyun/qyun.sh -O qyun.sh && chmod 0777 qyun.sh  && bash qyun.sh 
	exit 0
fi 
if [ $install_type == 2 ];then
    wget -q https://raw.githubusercontent.com/Demontisa/ML/main/op/fas/fas.sh -O fas.sh && chmod 0777 fas.sh  && bash fas.sh
	exit 0
fi 
if [ $install_type == 3 ];then
    wget -q https://raw.githubusercontent.com/Demontisa/ML/main/op/kyun/kyun.sh -O kyun.sh && chmod 0777 kyun.sh  && bash kyun.sh
	exit 0
fi 
if [ $install_type == 4 ];then
    wget -q https://raw.githubusercontent.com/oooldking/script/master/superspeed.sh -O superspeed.sh && chmod 0777 superspeed.sh  && bash superspeed.sh
	exit 0
fi 
